common:
    analysissqlserver:
        database: easy_Analyse
        password: easy
        port: 1433
        server: 192.168.127.245
        user: easy
    basicsqlserver:
        database: easy_Basic
        password: easy
        port: 1433
        server: 192.168.127.245
        user: easy
    datasqlserver:
        database: easy_Data
        password: easy
        port: 1433
        server: 192.168.127.245
        user: easy
    elasticsearch:
        address: https://192.168.127.250:9200,https://192.168.127.252:9200
        cacert: ./certs/http_ca.crt
        mfgpartindex: mfgpart_easy
        password: OWGVDa4515owSd7fBXdX
        pricestockindex: stockprice
        timeout: 30
        username: elastic
    jobsconfig:
        funcswitch:
            attributesdel: true
    jobsqlserver:
        database: easy_Job
        password: easy
        port: 1433
        server: 192.168.127.245
        user: easy
    managesqlserver:
        database: easy_Manage
        password: easy
        port: 1433
        server: 192.168.127.245
        user: easy
    redis:
        address: 192.168.127.246:32200
        db: 2
        password: easy@2024
    webui:
        root: ./manage
