common:
    elasticsearch:
        address: https://192.168.127.250:9200,https://192.168.127.252:9200
        cacert: ./certs/http_ca.crt
        productindex: product_easy
        password: OWGVDa4515owSd7fBXdX
        pricestockindex: stockprice
        timeout: 30
        username: elastic
    jobsconfig:
        funcswitch:
            attributesdel: true
    redis:
        address: 192.168.127.246:32200
        db: 2
        password: easy@2024
    webui:
        root: ./manage
