tenants:
  - id: analysis
    database:
      driver: sqlserver
      host: 192.168.127.245
      username: easy
      password: easy
  - id: basic
    database:
      driver: sqlserver
      host: 192.168.127.245
      username: easy
      password: easy
  - id: data
    database:
      driver: sqlserver
      host: 192.168.127.245
      username: easy
      password: easy
  - id: job
    database:
      driver: sqlserver
      host: 192.168.127.245
      username: easy
      password: easy
  - id: manage
    database:
      driver: sqlserver
      host: 192.168.127.245
      username: easy
      password: easy
tables:
  - name: products
    database: basic
  - name: prices
    database: data