common:
  logdb:
    connstring: server=192.168.127.245;user id=easy;password=easy;database=easy_Log
    ticker: 5
    channum: 100
  server:
    name: easyes
    runmode: debug
    testaddr: localhost:6060
    addr: grpc.easy.dev:8088
    tls: true
    cert: ./certs/server.crt
    key: ./certs/server.key
  elasticsearch:
    address: https://192.168.127.250:9200,https://192.168.127.252:9200
    cacert: ./certs/http_ca.crt
    productindex: product_easy
    password: OWGVDa4515owSd7fBXdX
    pricestockindex: stockprice
    username: elastic
    timeout: 30
    boots: [4,3,3,4,4,12,13,14,15]