// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.22.0
// source: protos/messages/pricesearch.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单型号下的产品价格搜索参数
type PriceSearchParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID  int32 `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	From int32 `protobuf:"varint,3,opt,name=From,proto3" json:"From,omitempty"`
}

func (x *PriceSearchParam) Reset() {
	*x = PriceSearchParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_pricesearch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceSearchParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceSearchParam) ProtoMessage() {}

func (x *PriceSearchParam) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_pricesearch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceSearchParam.ProtoReflect.Descriptor instead.
func (*PriceSearchParam) Descriptor() ([]byte, []int) {
	return file_protos_messages_pricesearch_proto_rawDescGZIP(), []int{0}
}

func (x *PriceSearchParam) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *PriceSearchParam) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PriceSearchParam) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

// 单型号下的产品价格返回结果
type SearchPricesResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID   int32           `protobuf:"varint,1,opt,name=PID,proto3" json:"PID,omitempty"`
	Total int32           `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	From  int32           `protobuf:"varint,3,opt,name=From,proto3" json:"From,omitempty"`
	Size  int32           `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	Data  []*ESStockPrice `protobuf:"bytes,5,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *SearchPricesResult) Reset() {
	*x = SearchPricesResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_pricesearch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPricesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPricesResult) ProtoMessage() {}

func (x *SearchPricesResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_pricesearch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPricesResult.ProtoReflect.Descriptor instead.
func (*SearchPricesResult) Descriptor() ([]byte, []int) {
	return file_protos_messages_pricesearch_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPricesResult) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *SearchPricesResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchPricesResult) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SearchPricesResult) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchPricesResult) GetData() []*ESStockPrice {
	if x != nil {
		return x.Data
	}
	return nil
}

// 产品价格
type ESStockPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SID                string  `protobuf:"bytes,1,opt,name=SID,proto3" json:"SID,omitempty"`
	ProductName        string  `protobuf:"bytes,2,opt,name=ProductName,proto3" json:"ProductName,omitempty"`
	DistributorType    int32   `protobuf:"varint,5,opt,name=DistributorType,proto3" json:"DistributorType,omitempty"`
	DistributorID      int32   `protobuf:"varint,6,opt,name=DistributorID,proto3" json:"DistributorID,omitempty"`
	Distributor        string  `protobuf:"bytes,7,opt,name=Distributor,proto3" json:"Distributor,omitempty"`
	StockNum           int32   `protobuf:"varint,8,opt,name=StockNum,proto3" json:"StockNum,omitempty"`
	Currency           string  `protobuf:"bytes,9,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Price1             float32 `protobuf:"fixed32,10,opt,name=Price1,proto3" json:"Price1,omitempty"`
	Price2             float32 `protobuf:"fixed32,11,opt,name=Price2,proto3" json:"Price2,omitempty"`
	Price3             float32 `protobuf:"fixed32,12,opt,name=Price3,proto3" json:"Price3,omitempty"`
	Price4             float32 `protobuf:"fixed32,13,opt,name=Price4,proto3" json:"Price4,omitempty"`
	Price5             float32 `protobuf:"fixed32,14,opt,name=Price5,proto3" json:"Price5,omitempty"`
	UpdatedUtc         string  `protobuf:"bytes,15,opt,name=UpdatedUtc,proto3" json:"UpdatedUtc,omitempty"`
	IsAuthorizeddealer bool    `protobuf:"varint,16,opt,name=IsAuthorizeddealer,proto3" json:"IsAuthorizeddealer,omitempty"`
}

func (x *ESStockPrice) Reset() {
	*x = ESStockPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_messages_pricesearch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESStockPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESStockPrice) ProtoMessage() {}

func (x *ESStockPrice) ProtoReflect() protoreflect.Message {
	mi := &file_protos_messages_pricesearch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESStockPrice.ProtoReflect.Descriptor instead.
func (*ESStockPrice) Descriptor() ([]byte, []int) {
	return file_protos_messages_pricesearch_proto_rawDescGZIP(), []int{2}
}

func (x *ESStockPrice) GetSID() string {
	if x != nil {
		return x.SID
	}
	return ""
}

func (x *ESStockPrice) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ESStockPrice) GetDistributorType() int32 {
	if x != nil {
		return x.DistributorType
	}
	return 0
}

func (x *ESStockPrice) GetDistributorID() int32 {
	if x != nil {
		return x.DistributorID
	}
	return 0
}

func (x *ESStockPrice) GetDistributor() string {
	if x != nil {
		return x.Distributor
	}
	return ""
}

func (x *ESStockPrice) GetStockNum() int32 {
	if x != nil {
		return x.StockNum
	}
	return 0
}

func (x *ESStockPrice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ESStockPrice) GetPrice1() float32 {
	if x != nil {
		return x.Price1
	}
	return 0
}

func (x *ESStockPrice) GetPrice2() float32 {
	if x != nil {
		return x.Price2
	}
	return 0
}

func (x *ESStockPrice) GetPrice3() float32 {
	if x != nil {
		return x.Price3
	}
	return 0
}

func (x *ESStockPrice) GetPrice4() float32 {
	if x != nil {
		return x.Price4
	}
	return 0
}

func (x *ESStockPrice) GetPrice5() float32 {
	if x != nil {
		return x.Price5
	}
	return 0
}

func (x *ESStockPrice) GetUpdatedUtc() string {
	if x != nil {
		return x.UpdatedUtc
	}
	return ""
}

func (x *ESStockPrice) GetIsAuthorizeddealer() bool {
	if x != nil {
		return x.IsAuthorizeddealer
	}
	return false
}

var File_protos_messages_pricesearch_proto protoreflect.FileDescriptor

var file_protos_messages_pricesearch_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x4c, 0x0a,
	0x10, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x50, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x90, 0x01, 0x0a, 0x12,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x50, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72,
	0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x45, 0x53, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xb4,
	0x03, 0x0a, 0x0c, 0x45, 0x53, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x53, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x49,
	0x44, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x6f,
	0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x31, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32, 0x12, 0x16, 0x0a,
	0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x33, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x34, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x34, 0x12, 0x16, 0x0a,
	0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x35, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x35, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x55, 0x74, 0x63, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x55, 0x74, 0x63, 0x12, 0x2e, 0x0a, 0x12, 0x49, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x65, 0x64, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x12, 0x49, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x64,
	0x65, 0x61, 0x6c, 0x65, 0x72, 0x42, 0x37, 0x5a, 0x19, 0x65, 0x61, 0x73, 0x79, 0x6d, 0x73, 0x2d,
	0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0xaa, 0x02, 0x19, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_messages_pricesearch_proto_rawDescOnce sync.Once
	file_protos_messages_pricesearch_proto_rawDescData = file_protos_messages_pricesearch_proto_rawDesc
)

func file_protos_messages_pricesearch_proto_rawDescGZIP() []byte {
	file_protos_messages_pricesearch_proto_rawDescOnce.Do(func() {
		file_protos_messages_pricesearch_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_messages_pricesearch_proto_rawDescData)
	})
	return file_protos_messages_pricesearch_proto_rawDescData
}

var file_protos_messages_pricesearch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_messages_pricesearch_proto_goTypes = []any{
	(*PriceSearchParam)(nil),   // 0: messages.PriceSearchParam
	(*SearchPricesResult)(nil), // 1: messages.SearchPricesResult
	(*ESStockPrice)(nil),       // 2: messages.ESStockPrice
}
var file_protos_messages_pricesearch_proto_depIdxs = []int32{
	2, // 0: messages.SearchPricesResult.Data:type_name -> messages.ESStockPrice
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_messages_pricesearch_proto_init() }
func file_protos_messages_pricesearch_proto_init() {
	if File_protos_messages_pricesearch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_messages_pricesearch_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PriceSearchParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messages_pricesearch_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SearchPricesResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_messages_pricesearch_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ESStockPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_messages_pricesearch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_messages_pricesearch_proto_goTypes,
		DependencyIndexes: file_protos_messages_pricesearch_proto_depIdxs,
		MessageInfos:      file_protos_messages_pricesearch_proto_msgTypes,
	}.Build()
	File_protos_messages_pricesearch_proto = out.File
	file_protos_messages_pricesearch_proto_rawDesc = nil
	file_protos_messages_pricesearch_proto_goTypes = nil
	file_protos_messages_pricesearch_proto_depIdxs = nil
}
